# Generated by Django 4.1 on 2022-08-04 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodpressure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodpressure',
            name='diastolic',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bloodpressure',
            name='pulse',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bloodpressure',
            name='systolic',
            field=models.IntegerField(),
        ),
    ]
